SELECT * FROM ADDRESSES;              

INSERT INTO ADDRESSES (ADDRID ,ADDR ,LOCATIONID )
SELECT 6,'135.132.64.143', 4
WHERE NOT EXISTS(SELECT * FROM ADDRESSES WHERE ADDR='135.132.64.143');


SELECT * FROM CONNECTIONS;

INSERT INTO CONNECTIONS (CONNECTIONID, FROMADDR, TOADDR, ROUTEID)
SELECT 6,3,4,0
WHERE NOT EXISTS(SELECT * FROM CONNECTIONS WHERE FROMADDR = 3 AND TOADDR=4);


SELECT * FROM LOCATIONS;

INSERT INTO LOCATIONS (LOCATIONID, COUNTRY ,CITY ,LATITUDE ,LONGITUDE )
SELECT  5,'SV', 'Uppsala', 55.3333, 19.05
WHERE NOT EXISTS(SELECT * FROM LOCATIONS WHERE COUNTRY='SV' AND CITY ='Uppsala');


SELECT * FROM PACKETS;              

INSERT INTO PACKETS (PACKETID , CONNECTIONID , TIME, TIMEPERIOD , HITCOUNT , PROTOCOLID , TYPEID  )
SELECT 6,7,'2014-02-27 20:26:05.0','00:00:05',20,1,1
WHERE NOT EXISTS(SELECT * FROM PACKETS WHERE PACKETID=6);


SELECT * FROM PROTOCOLS;

INSERT INTO PROTOCOLS (PROTOCOLID,NAME)
SELECT 1, 'TCP'
WHERE NOT EXISTS(SELECT * FROM PROTOCOLS WHERE NAME='TCP');


SELECT * FROM TYPES;

INSERT INTO TYPES  ( TYPEID ,NAME)
SELECT 4, 'HEMLIG'
WHERE NOT EXISTS(SELECT * FROM TYPES WHERE NAME='HEMLIG');